{{- include "zeebeGatewayRename" $ -}}
{{- if .Values.zeebe.enabled -}}
kind: ConfigMap
metadata:
  name: {{ include "zeebe.fullname.gateway" . }}
  labels:
    {{- include "zeebe.labels.gateway" . | nindent 4 }}
apiVersion: v1
data:
  gateway-log4j2.xml: |
{{- if .Values.zeebeGateway.log4j2 }}
    {{ .Values.zeebeGateway.log4j2 | indent 4 | trim }}
{{- end }}
{{- if .Values.zeebeGateway.configuration }}
  application.yaml: |
    {{ .Values.zeebeGateway.configuration | indent 4 | trim }}
{{- end }}
{{- range $key, $val := .Values.zeebeGateway.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
{{- end }}
{{- end }}
