apiVersion: v2
appVersion: "1.3.1"
description: Zeebe Cluster Helm Chart for Kubernetes
name: zeebe-cluster-helm
type: application
version: 1.3.4
icon: https://helm.camunda.io/imgs/zeebe-logo.png
annotations:
  artifacthub.io/changes: |
    - rewrite zeebe chart
  artifacthub.io/containsSecurityUpdates: "false"
