apiVersion: v2
appVersion: "1.3.1"
description: Zeebe Helm Chart for Kubernetes
name: zeebe
type: application
version: 0.0.4
icon: https://helm.camunda.io/imgs/zeebe-logo.png
annotations:
  artifacthub.io/changes: |
    - rewrite zeebe chart
  artifacthub.io/containsSecurityUpdates: "false"
