apiVersion: v2
name: camunda-platform
version: 9.0.0
appVersion: 8.4.x
description: |
  Camunda 8 Self-Managed Helm charts.
  Camunda's process automation platform allows developers to design, automate and improve processes.
type: application
icon: https://helm.camunda.io/imgs/camunda.svg
home: https://docs.camunda.io/docs/self-managed/overview/
sources:
  - https://github.com/camunda/camunda-platform-helm
keywords:
  - bpm
  - bpmn
  - camunda-platform
  - dmn
  - process-engine
  - workflow
dependencies:
  # Camunda charts.
  - name: identity
    version: 9.0.0
    condition: "identity.enabled"
    import-values:
      # START DEV COMMENT 
      # NOTE: This is used to share Identity image details with its subchart Keycloak.
      #       It should be part of Identity but Helm 3 missing this option currently (v3.10.x).
      # TODO: Move this to Identity subchart once "export-values" is implemented.
      #       https://github.com/helm/helm/pull/10804
      # END DEV COMMENT
      - child: image
        parent: global.identity.image
  # Dependency charts.
  - name: elasticsearch
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 19.13.15
    condition: "elasticsearch.enabled"
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
    condition: "postgresql.enabled"
  # Helpers charts.
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
  - name: aabouzaid
    email: ahmed.abouzaid@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Camunda 8 docs
      url: https://docs.camunda.io/
    - name: Camunda 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: "use new Identity variables for auth configuration"
    - kind: changed
      description: "resolve issues with web modeler deployment when using OIDC"
    - kind: changed
      description: "use correct web modeler audiences"
    - kind: changed
      description: "update helm chart version schema"
    - kind: changed
      description: "remove deprecated tasklist graphql playground"
    - kind: changed
      description: "upgrade elasticsearch image from 8.8.2 to 8.9.2"
    - kind: changed
      description: "fail if Multi-Tenancy requirements are not met"
    - kind: changed
      description: "upgrade keycloak chart from 16.1.7 to 17.3.5"
