{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity.fullname" . }}-spring-config
  labels: {{- include "identity.labels" . | nindent 4 }}
  annotations: {{- toYaml  .Values.global.annotations | nindent 4 }}
data:
  {{- if .Values.configuration }}
  application.yaml: |
    {{ .Values.configuration | indent 4 | trim }}
  {{- else }}
  application.yaml: |
    identity:
    {{- if .Values.fullURL }}
      url: {{ tpl .Values.fullURL $ | quote }}
    {{- else }}
      url: {{ include "identity.internalUrl" . | quote }}
    {{- end }}
      authProvider:
        {{- if ne .Values.global.identity.auth.type "KEYCLOAK" }}
        type: {{ include "camundaPlatform.authType" . | quote }}
        {{- end }}
        issuer-url: {{ include "camundaPlatform.authIssuerUrl" . | quote }}
        backend-url: {{ include "identity.issuerBackendUrl" . | quote }}

      {{- if ne .Values.global.identity.auth.type "KEYCLOAK" }}
      component-presets:
        identity:
          apis:
            - name: "Camunda Identity Resource Server"
              audience: ${IDENTITY_AUDIENCE:camunda-identity-resource-server}
              permissions:
                - definition: read
                  description: "Read permission"
                - definition: "read:users"
                  description: "Read users permission"
                - definition: write
                  description: "Write permission"
          roles:
            - name: "Identity"
              description: "Provides full access to Identity"
              permissions:
                - audience: ${IDENTITY_AUDIENCE:camunda-identity-resource-server}
                  definition: read
                - audience: ${IDENTITY_AUDIENCE:camunda-identity-resource-server}
                  definition: write
        operate:
          apis:
            - name: Operate API
              audience: {{ include "operate.authAudience" . | default "operate-api" | quote }}
              permissions:
                - definition: read:*
                  description: "Read permission"
                - definition: write:*
                  description: "Write permission"
          roles:
            - name: "Operate"
              description: "Grants full access to Operate"
              permissions:
                - audience: {{ include "operate.authAudience" . | default "operate-api" | quote }}
                  definition: read:*
                - audience: {{ include "operate.authAudience" . | default "operate-api" | quote }}
                  definition: write:*
        tasklist:
          apis:
            - name: Tasklist API
              audience: {{ include "tasklist.authAudience" . | default "tasklist-api" | quote }}
              permissions:
                - definition: read:*
                  description: "Read permission"
                - definition: write:*
                  description: "Write permission"
          roles:
            - name: "Tasklist"
              description: "Grants full access to Tasklist"
              permissions:
                - audience: {{ include "tasklist.authAudience" . | default "tasklist-api" | quote }}
                  definition: read:*
                - audience: {{ include "tasklist.authAudience" . | default "tasklist-api" | quote }}
                  definition: write:*
        zeebe:
          apis:
            - name: Zeebe API
              audience: {{ .Values.global.identity.auth.zeebe.audience | default "zeebe-api" | quote }}
              permissions:
                - definition: write:*
                  description: "Write permission"
          roles:
            - name: "Zeebe"
              description: "Grants full access to the Zeebe API"
              permissions:
                - audience: {{ .Values.global.identity.auth.zeebe.audience | default "zeebe-api" | quote }}
                  definition: write:*
        optimize:
          apis:
            - name: Optimize API
              audience: {{ include "optimize.authAudience" . | default "optimize-api" | quote }}
              permissions:
                - definition: write:*
                  description: "Write permission"
          roles:
            - name: "Optimize"
              description: "Grants full access to Optimize"
              permissions:
                - audience: {{ include "optimize.authAudience" . | default "optimize-api" | quote }}
                  definition: write:*
                - audience: {{ include "identity.authAudience" . | default "camunda-identity" | quote }}
                  definition: read:users
        webmodeler:
          apis:
            - name: Web Modeler Internal API
              audience: {{ .Values.global.identity.auth.webModeler.clientApiAudience | default "web-modeler-api" | quote }}
              permissions:
                - definition: write:*
                  description: "Write permission"
            - name: Web Modeler API
              audience: {{ .Values.global.identity.auth.webModeler.publicApiAudience | default "web-modeler-public-api" | quote }}
              permissions:
                - definition: create:*
                  description: "Allows create access for all resources"
                - definition: read:*
                  description: "Allows read access to all resources"
                - definition: update:*
                  description: "Allows update access to all resources"
                - definition: delete:*
                  description: "Allows delete access for all resources"
          roles:
            - name: "Web Modeler"
              description: "Grants full access to Web Modeler"
              permissions:
                - audience: {{ .Values.global.identity.auth.webModeler.clientApiAudience | default "web-modeler-api" | quote }}
                  definition: write:*
                - audience: {{ include "identity.authAudience" . | default "camunda-identity-resource-server" | quote }}
                  definition: read:users
        console:
          apis:
            - name: Console API
              audience: {{ .Values.global.identity.auth.console.audience | default "console-api" | quote }}
              permissions:
                - definition: write:*
                  description: "Write permission"
          roles:
            - name: "Console"
              description: "Grants full access to Console"
              permissions:
                - audience: {{ .Values.global.identity.auth.console.audience | default "console-api" | quote }}
                  definition: write:*
      {{- end }}

    {{- if .Values.global.identity.auth.enabled }}
    {{- if eq .Values.global.identity.auth.type "KEYCLOAK"}}
    keycloak:
      environment:
        clients:
        - name: Identity
          id: {{ include "identity.authClientId" . | default "camunda-identity" | quote }}
          type: CONFIDENTIAL
          secret: {{ include "identity.authClientSecret" . | quote }}
          {{- if .Values.fullURL }}
          root-url: {{ tpl .Values.fullURL $ | quote }}
          {{- else }}
          root-url: {{ printf "%s%s" "${IDENTITY_URL:http://localhost:${SERVER_PORT:8080}" .Values.contextPath }}
          {{- end }}
          redirect-uris:
            - "/auth/login-callback"
      presets:
        tasklist:
          clients:
            - name: Tasklist
              id: tasklist
              type: confidential
              secret: ${KEYCLOAK_INIT_TASKLIST_SECRET:}
              root-url: {{ tpl .Values.global.identity.auth.tasklist.redirectUrl $ | quote }}
              redirect-uris:
                - "/identity-callback"
        operate:
          clients:
            - name: Operate
              id: ${KEYCLOAK_INIT_OPERATE_CLIENT_ID:operate}
              type: confidential
              secret: ${KEYCLOAK_INIT_OPERATE_SECRET:}
              root-url: {{ tpl .Values.global.identity.auth.operate.redirectUrl $ | quote }}
              redirect-uris:
                - "/identity-callback"
        optimize:
          clients:
            - name: Optimize
              id: ${KEYCLOAK_INIT_OPTIMIZE_CLIENT_ID:optimize}
              type: confidential
              secret: ${KEYCLOAK_INIT_OPTIMIZE_SECRET:}
              root-url: {{ tpl .Values.global.identity.auth.optimize.redirectUrl $ | quote }}
              redirect-uris:
                - "/api/authentication/callback"
        console:
          clients:
            - name: "Console"
              id: ${KEYCLOAK_INIT_CONSOLE_CLIENT_ID:console}
              type: public
              root-url: {{ tpl .Values.global.identity.auth.console.redirectUrl $ | quote }}
              redirect-uris:
                - "/"

    {{- end }}
    {{- end }}
    server:
      port: 8080
    {{- if .Values.contextPath }}
      servlet:
        context-path: {{ .Values.contextPath | quote }}
    {{- end }}

    spring:
    {{- if .Values.global.identity.auth.enabled }}
      profiles:
        active: {{ eq .Values.global.identity.auth.type "KEYCLOAK" | ternary "keycloak" "oidc" }}
    {{- end }}

    {{- if ne .Values.global.identity.auth.type "KEYCLOAK" }}
    camunda:
      identity:
        baseUrl: {{ include "identity.internalUrl" . | quote }}
        issuer: {{ include "camundaPlatform.authIssuerUrl" . | quote }}
        issuerBackendUrl: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
    {{- end }}
        
  {{- end }}
  {{- range $key, $val := .Values.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
