{{- if and (.Values.global.operate.auth.identity.enabled) (not .Values.global.operate.auth.identity.existingSecret) }}
{{- $secretName := include "identity.secretNameOperateIdentity" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "identity.labels" . | nindent 4 }}
type: Opaque
data:
  operate-secret: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "operate-secret" "length" 10 "providedValues" (list "global.operate.auth.identity.operateSecret") "context" $) }}
{{- end }}
