{{- if and (.Values.global.tasklist.auth.identity.enabled) (not .Values.global.tasklist.auth.identity.existingSecret) }}
{{- $secretName := include "identity.secretNameTasklistIdentity" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "identity.labels" . | nindent 4 }}
type: Opaque
data:
  tasklist-secret: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "tasklist-secret" "length" 10 "providedValues" (list "global.operate.auth.identity.tasklistSecret") "context" $) }}
{{- end }}
