{{- if and (.Values.global.identity.auth.enabled) (typeIs "string" .Values.global.identity.auth.identity.existingSecret) }}
{{/*{{- if and (.Values.global.identity.auth.enabled) (not .Values.global.identity.auth.identity.existingSecret) }}*/}}
{{- $secretName := include "camundaPlatform.identitySecretName" (dict "context" . "component" "identity") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "camundaPlatform.identityLabels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.global.identity.auth.identity.existingSecretKey }}: "{{ .Values.global.identity.auth.identity.existingSecret | b64enc }}"
{{- end }}
