{{- if .Values.global.opensearch.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-password
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.global.opensearch.auth.password | b64enc }}
{{- end }}

