{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zeebe-tasklist.fullname" . }}
  labels: {{ include "zeebe-tasklist.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name:  {{ include "zeebe-tasklist.fullname" . }}
                port:
                  number: 80
{{- end }}
