apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasklist.fullname" . }}
  labels:
    app: {{ include "tasklist.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ include "tasklist.fullname" . }}
