{{- if .Values.prometheusServiceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ccms-service-monitor
  labels: {{- include "ccsm.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.global.labels | nindent 6 }}
  endpoints:
    - honorLabels: true
      port: http
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
{{- end }}
