# Default values for Camunda Cloud Self Managed helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # Annotations to apply to all deployments
  annotations: {}
  labels:
    app: camunda-cloud-self-managed
  image:
    # global.image.repository is net set here, otherwise it will overwrite the values from the sub chart
    #    repository: camunda/zeebe
    tag: 1.3.1
    pullPolicy: IfNotPresent
    pullSecrets: [ ]
  elasticsearch:
    disableExporter: false
    url:
    host: "elasticsearch-master"
    port: 9200
    clusterName: "elasticsearch"
    prefix: zeebe-record
  zeebeClusterName: "{{ .Release.Name }}-zeebe"
  zeebePort: 26500

zeebe:
  enabled: true

operate:
  enabled: true

elasticsearch:
  enabled: true
  imageTag: 7.16.2
  extraEnvs:
    - name: "xpack.security.enabled"
      value: "false"

kibana:
  enabled: false
  imageTag: 7.16.2

prometheus:
  enabled: false
  servicemonitor:
    enabled: false
