{{- if .Values.webModeler.enabled -}}
{{- $useExternalDatabasePassword := and (not .Values.postgresql.enabled) (include "webModeler.restapi.explicitPassword" .) (typeIs "string" .Values.webModeler.restapi.externalDatabase.existingSecret)) }}
{{- $useSmtpPassword := (and (not (typeIs "map[string]interface {}" .Values.webModeler.restapi.mail.existingSecret)) (or (.Values.webModeler.restapi.mail.smtpPassword) (.Values.webModeler.restapi.mail.existingSecret)) ) }}
{{- if or $useExternalDatabasePassword $useSmtpPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webModeler.restapi.fullname" . }}
  labels: {{- include "webModeler.restapi.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
type: Opaque
data:
  {{- if $useExternalDatabasePassword }}
  database-password: {{ (include "webModeler.restapi.explicitPassword" .) | b64enc }}
  {{- end }}
  {{- if $useSmtpPassword }}
  smtp-password: {{ .Values.webModeler.restapi.mail.existingSecret | default .Values.webModeler.restapi.mail.smtpPassword | b64enc }}
  {{- end }}

{{- end }}
{{- end }}
