{{- if .Values.operate.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operate.fullname" . }}-archiver
  labels:
    {{- include "operate.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "operate.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "operate.labels" . | nindent 8 }}
        {{- if .Values.operate.podLabels }}
          {{- toYaml .Values.operate.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/operate/archiver-configmap.yaml") . | sha256sum }}
      {{- if .Values.operate.podAnnotations }}
        {{- toYaml .Values.operate.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- include "operate.imagePullSecrets" . | nindent 8 }}
      initContainers:
        {{- tpl (.Values.operate.initContainers | default list | toYaml | nindent 8) $ }}
      containers:
        {{- include "operate.spec.template.spec.containers" . }}
      volumes:
        - name: config
          configMap:
            name: {{ include "operate.fullname" . }}-archiver-configuration
            defaultMode: {{ .Values.operate.configMap.defaultMode }}
        {{- include "operate.spec.template.spec.volumes" . }}
      {{- if .Values.operate.serviceAccount.name }}
      serviceAccountName: {{ .Values.operate.serviceAccount.name }}
      {{- end }}
      {{- if .Values.operate.podSecurityContext }}
      securityContext: {{- toYaml .Values.operate.podSecurityContext | nindent 8 }}
      {{- end }}
{{- with .Values.operate.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.operate.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.operate.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
