apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: remote-ccsm-helm
  app.kubernetes.io/name: ccsm-helm

resources:
- ccsm-helm-namespace.yaml
- ccsm-helm-serviceaccount.yaml
- ccsm-helm-rolebinding.yaml
- ccsm-helm-role.yaml
