{{- if .Values.webModeler.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webModeler.fullname" . }}-webapp
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
data:
  pusher-app-id: web-modeler
  pusher-app-key: {{ randAlphaNum 20 }}
  {{- if .Values.webModeler.webapp.configuration }}
  application.yaml: |
    {{ .Values.webModeler.webapp.configuration | indent 4 | trim }}
  {{- else }}
  application.yaml: |
    httpWorkers: 2
    restapi:
      host: {{ include "webModeler.restapi.fullname" . | quote }}
      port: {{ .Values.webModeler.restapi.service.port }}
      managementPort: {{ .Values.webModeler.restapi.service.managementPort }}
    server:
      url: {{ tpl .Values.global.identity.auth.webModeler.redirectUrl $ | quote }}
      httpsOnly: {{ hasPrefix "https://" (tpl .Values.global.identity.auth.webModeler.redirectUrl $) | quote }}
      oAuth2:
        type: {{ include "camundaPlatform.authType" . | quote }}
        clientId: {{ include "webModeler.authClientId" . | quote }}
        token:
          jwksUrl: {{ include "camundaPlatform.authIssuerBackendUrlCertsEndpoint" . | quote }}
          audience: {{ include "webModeler.authClientApiAudience" . | quote }}
          issuer: {{ include "camundaPlatform.authIssuerUrl" . | quote }}
    pusher:
      host: {{ include "webModeler.websockets.fullname" . | quote }}
      port: {{ .Values.webModeler.websockets.service.port }}
    client:
      pusher:
        host: {{ include "webModeler.publicWebsocketHost" . | quote }}
        port: {{ include "webModeler.publicWebsocketPort" . | quote }}
        {{- if and .Values.global.ingress.enabled .Values.webModeler.contextPath }}
        path: {{ include "webModeler.websocketContextPath" . | quote }}
        {{- end }}
        forceTLS: {{ include "webModeler.websocketTlsEnabled" . | quote }}
    {{- if .Values.identity.enabled }}
    identity:
      baseUrl: {{ include "webModeler.identityBaseUrl" . | quote }}
    {{- end }}

  {{- end }}
  {{- range $key, $val := .Values.webModeler.webapp.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
