{{- if .Values.connectors.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connectors.fullname" . }}
  labels:
    {{- include "connectors.labels" . | nindent 4 }}
data:
  {{- if .Values.connectors.configuration }}
  application.yml: |
    {{ .Values.connectors.configuration | indent 4 | trim }}
  {{- end }}

  {{- range $key, $val := .Values.connectors.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
