name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Format
      uses: actions/github-script@v3
      with:
       script: |
        go fmt -v ./...
        if [ -n "$(git status --porcelain)" ]
        then
          core.setFailed('Some files are not following the go format, run gofmt and fix your files.')
        fi
     
    - name: Test
      run: go test -v ./...
