name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Format
      run: |
        go fmt -v ./...
        diff=$(git status --porcelain)
        if [ -n "$diff" ]
        then
          echo "Some files are not following the go format ($diff), run gofmt and fix your files."
          exit 1
        fi
     
    - name: Test
      run: go test -v ./...
