name: Helm Lint Charts

on:
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: { }
env:
  HELM_VERSION: 3.6.3

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"
      - name: Add stable helm repo
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add stable https://charts.helm.sh/stable
          helm repo update
      - name: Create and Print Helm Templates
        run: |
          for i in charts/*; do helm template test $i; done

      - name: Get Helm Deps
        run: |
          helm dependency build charts/zeebe-full-helm
          helm dependency build charts/zeebe-cluster-helm
          helm dependency build charts/zeebe-zeeqs-helm
      
      - name: Run Helm lint 
        run: |
          helm lint --strict charts/*
